name: yorukler_giyim
description: "Yörükler Giyim"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  intl: ^0.19.0
  csv: ^5.1.1
  file_picker: ^10.1.9
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/simge.png
    - assets/splash_bg.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/simge.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_bg.png
  android: true
  ios: true
  fullscreen: true 