import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';
import 'dart:convert';

enum EntryType {
  gelir,
  gider,
  mevcut,
  borc,
}

enum IncomeExpenseCategory {
  // Gelir kategorileri
  sabitGelir(EntryType.gelir, 'Sabit Gelirler'),
  gunlukGelir(EntryType.gelir, 'Günlük Gelirler'),
  
  // Gider kategorileri
  sabitGider(EntryType.gider, 'Sabit Giderler'),
  gunlukGider(EntryType.gider, 'Günlük Giderler'),
  
  // Mevcut kategorileri
  nakit(EntryType.mevcut, 'Eldeki Nakit'),
  alacak(EntryType.mevcut, 'Alacaklar'),
  stok(EntryType.mevcut, 'Toplam Stok'),
  
  // Borç kategorileri
  bankaBorcu(EntryType.borc, 'Banka Borcu'),
  toptanciBorcu(EntryType.borc, 'Toptancı Borcu'),
  tlBorcu(EntryType.borc, 'TL ile Borç'),
  dovizBorcu(EntryType.borc, 'Döviz Borcu'),
  emtiaBorcu(EntryType.borc, 'Emtia Borcu');

  final EntryType entryType;
  final String categoryLabel;

  const IncomeExpenseCategory(this.entryType, this.categoryLabel);
}

class IncomeExpenseEntry {
  final String id;
  final String type;
  final String category;
  final String description;
  final double amount;
  final DateTime date;
  final bool isAutoGenerated;

  IncomeExpenseEntry({
    String? id,
    required this.type,
    required this.category,
    required this.description,
    required this.amount,
    required this.date,
    this.isAutoGenerated = false,
  }) : id = id ?? const Uuid().v4();

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'type': type,
      'category': category,
      'description': description,
      'amount': amount,
      'date': date.toIso8601String(),
      'isAutoGenerated': isAutoGenerated,
    };
  }

  String toJson() {
    return jsonEncode(toMap());
  }

  factory IncomeExpenseEntry.fromMap(Map<String, dynamic> map) {
    return IncomeExpenseEntry(
      id: map['id'] as String,
      type: map['type'] as String,
      category: map['category'] as String,
      description: map['description'] as String,
      amount: (map['amount'] as num).toDouble(),
      date: DateTime.parse(map['date'] as String),
      isAutoGenerated: map['isAutoGenerated'] as bool? ?? false,
    );
  }

  factory IncomeExpenseEntry.fromJson(String json) {
    return IncomeExpenseEntry.fromMap(jsonDecode(json));
  }

  IncomeExpenseEntry copyWith({
    String? id,
    String? type,
    String? category,
    String? description,
    double? amount,
    DateTime? date,
    bool? isAutoGenerated,
  }) {
    return IncomeExpenseEntry(
      id: id ?? this.id,
      type: type ?? this.type,
      category: category ?? this.category,
      description: description ?? this.description,
      amount: amount ?? this.amount,
      date: date ?? this.date,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }
} 